### ISSUE TITLE
Adding .vscode/ folder to gitignore

### ISSUE THREAD

**Issue by mar-galho** [government-ai/flowt#11]
Just a small fix that prevents .vscode/ folders to be uploaded by accident to repo.

**Comment by rozeappletree** [comment]
Hey @ricardoprins. Nice to see you here. We have vs code related ignores @ https://github.com/government-ai/flowt/blob/c0fb5351e85319fa7b11b02b4fcf5c837e08cf9b/.gitignore#L224

**Comment by rozeappletree** [comment]
Merged #10

**Comment by mar-galho** [comment]
Weird! The folder wasn't being ignored by vscode here for some reason, check image below @rakesh4real

**Comment by mar-galho** [comment]
![image](https://user-images.githubusercontent.com/54654484/116005435-1df99100-a5c4-11eb-87c7-989d3920f6ff.png)
